platform :ios, '7.0'
use_frameworks!

xcodeproj 'CrepeInventoryApp/CrepeInventoryApp.xcodeproj/'

target 'CrepeInventoryApp' do
  pod 'Parse', '~> 1.3'
#  pod 'ParseUI', '~>1.1.3'
 # pod 'AFNetworking', '~> 2.5'
 # pod 'ORStackView', '~> 2.0'
 # pod 'SwiftyJSON', '~> 2.1'
end
